from pathlib import Path
marker=Path('.staging/applied-02')
if marker.exists(): raise SystemExit(0)
def replace(path, old, new):
 p=Path(path);s=p.read_text();assert s.count(old)==1,(path,old[:80],s.count(old));p.write_text(s.replace(old,new))
replace('apps/web/src/nodes.tsx','<strong>E2b1 · 目录状态同步</strong>','<strong>独立节点 · 默认目录摘要</strong>')
replace('apps/web/src/nodes.tsx','当前只支持回环服务上的独立进程。在线不代表任务正在运行；任务派发、代码修改和跨电脑连接尚未开放。','当前只支持回环服务上的独立进程。在线不代表任务正在运行；执行需要本人在节点单独授权，跨电脑连接尚未开放。')
replace('apps/web/src/nodes.tsx','配对并不允许项目成员执行代码。节点目前只连接与上报摘要，不使用任何模型账户。','配对本身只连接与上报摘要，不授予代码执行或模型账户权限。启用执行必须由本人在节点本机另行确认。')
replace('apps/web/src/nodes.tsx','”的节点凭证，停止后续同步。不会删除本地代码，也不会撤回此前已分享的摘要。','”的节点凭证，阻止后续同步和任务派发。活动执行会请求停止，但仍须等待节点确认。不会删除本地代码，也不能追回已分享的内容。')
replace('apps/web/src/team.tsx','<strong>开发环境尚未接入，不共享宿主机执行权限。</strong>','<strong>代码执行使用你明确授权的独立节点。</strong>')
replace('apps/web/src/team.tsx','这里可以真实管理任务、讨论、成果和成员。独立\n            Runner、远程部署与真实模型联调仍未完成；团队模式不启用模拟或原生执行，也不读取宿主机工具配置。','控制服务不使用宿主机工具与模型账户。配对默认只共享目录摘要，在节点本机单独启用后可由本人发起执行；跨电脑部署与真实模型联调仍未完成。')
replace('apps/web/src/App.tsx',"                : '无真实执行节点'}","                : team\n                  ? '执行须选择本人授权节点'\n                  : '无真实执行节点'}")
replace('apps/web/src/node-execution.tsx','先在“资源与设置”配对节点，然后在节点本机运行 enable-execution','先在“空间与账号”配对节点，然后在节点本机运行 enable-execution')
replace('apps/runner/src/cli.ts','不上传路径、文件名、文件内容、Git 远程地址或模型密钥；不接受代码执行命令。','本次配对只共享摘要，不上传路径、文件名、代码或模型密钥；启用执行须在本机另行确认。')
replace('AGENTS.md','**team-local** uses real accounts and project data permissions but forbids host execution.','**team-local** uses real accounts/project permissions and optional owner-authorized independent node execution, never the control host runtime.')
replace('AGENTS.md','Independent node identity and grants must land before team execution.','Only the separate owner-authorized node provider may dispatch work; native/mock control-host dispatch remains forbidden.')
replace('README.md','随后 `runner start` 发布执行能力。','随后运行 `npm run runner -- start --state /absolute/private-state` 发布执行能力。')
replace('README.md','| [下一步交付](docs/development/22-next-delivery.md) | 独立节点的执行授权、任务派发、停止与恢复 |','| [下一步交付](docs/development/22-next-delivery.md) | 节点持续工作、接续与远程协作的前置边界 |')
replace('tests/e2e/team.spec.ts',"member.getByRole('button', { name: '继续', exact: true })", "member.getByRole('button', { name: '在节点上执行', exact: true })")
marker.write_text('Align E2b2 scope and keep read-only users unable to execute.\n')
